spring:
  datasource:
    url: jdbc:mysql://localhost:3306/logger?createDatabaseIfNotExist=TRUE
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations:
      - classpath:db/migration

